/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.klijenti;

import domen.Klijent;
import domen.OpstiDomenskiObjekat;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import konstante.Konstante;
import kontroler.Kontroler;
import modelitabele.ModelTabeleKlijenti;
import transfer.ServerskiTransferObjekat;
import validation.FormValidator;

/**
 *
 * @author Miroslav
 */
public class RadSaKlijentima extends javax.swing.JDialog {

    /**
     * Creates new form RadSaKlijentima
     */
    public RadSaKlijentima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        UIManager.getLookAndFeelDefaults()
        .put("defaultFont", new Font("Arial", Font.BOLD, 18));
        initComponents();
        
        ModelTabeleKlijenti mt = new ModelTabeleKlijenti();
        tblKlijenti.setModel(mt);
        srediFormu();
        
        pretrazi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPib = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNazivKlijenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmailKlijenta = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga po nazivu klijenta");

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jLabel2.setText("pib");

        jLabel3.setText("Naziv klijenta");

        jLabel4.setText("Adresa");

        jLabel5.setText("Broj telefona");

        jLabel6.setText("Email klijenta");

        btnSacuvaj.setText("SACUUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("IZMENI");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("OBRISI");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDetalji.setText("Ucitaj detalje");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPib, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtNazivKlijenta)
                            .addComponent(txtAdresa)
                            .addComponent(txtEmailKlijenta)
                            .addComponent(txtBrojTelefona)))
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnDetalji)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNazivKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmailKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        boolean validnoPrazno = FormValidator.getInstance().validateEmpty(txtAdresa,txtBrojTelefona,txtEmailKlijenta,txtNazivKlijenta,txtPib);
        if(!validnoPrazno){
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }
        
        if(!FormValidator.getInstance().validateEmail(txtEmailKlijenta)){
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }
        
        String naziv = txtNazivKlijenta.getText();
        String adresa = txtAdresa.getText();
        String brojTelefona = txtBrojTelefona.getText();
        String emailKlijenta = txtEmailKlijenta.getText();
        try {
            int pib = Integer.parseInt(txtPib.getText());
            Klijent klijent = new Klijent(pib, naziv, adresa, brojTelefona, emailKlijenta);
            ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.IZMENI_KLIJENTA, klijent);
            JOptionPane.showMessageDialog(this, sto.getPoruka());
            if(sto.isUspesno()){
                srediFormu();
                pretrazi();
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pib mora biti broj");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        boolean validnoPrazno = FormValidator.getInstance().validateEmpty(txtAdresa,txtBrojTelefona,txtEmailKlijenta,txtNazivKlijenta,txtPib);
        if(!validnoPrazno){
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }
        
        if(!FormValidator.getInstance().validateEmail(txtEmailKlijenta)){
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }
        
        String naziv = txtNazivKlijenta.getText();
        String adresa = txtAdresa.getText();
        String brojTelefona = txtBrojTelefona.getText();
        String emailKlijenta = txtEmailKlijenta.getText();
        try {
            int pib = Integer.parseInt(txtPib.getText());
            Klijent klijent = new Klijent(pib, naziv, adresa, brojTelefona, emailKlijenta);
            ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.UNESI_KLIJENTA, klijent);
            JOptionPane.showMessageDialog(this, sto.getPoruka());
            if(sto.isUspesno()){
                srediFormu();
                pretrazi();
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pib mora biti broj");
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int red = tblKlijenti.getSelectedRow();
        
        if(red != -1){
            ModelTabeleKlijenti mtk = (ModelTabeleKlijenti) tblKlijenti.getModel();
            Klijent odabraniKlijent = mtk.vratiKlijenta(red);
            srediFormuZaIzmenu(odabraniKlijent);
        }else{
            JOptionPane.showMessageDialog(this, "Morate odabrati red");
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        try {
            int pib = Integer.parseInt(txtPib.getText());
            Klijent klijent = new Klijent(pib, "", "", "", "");
            ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.OBRISI_KLIJENTA, klijent);
            JOptionPane.showMessageDialog(this, sto.getPoruka());
            if(sto.isUspesno()){
                srediFormu();
                pretrazi();
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pib mora biti broj");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretrazi();
    }//GEN-LAST:event_btnPretraziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadSaKlijentima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadSaKlijentima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadSaKlijentima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadSaKlijentima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RadSaKlijentima dialog = new RadSaKlijentima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtEmailKlijenta;
    private javax.swing.JTextField txtNazivKlijenta;
    private javax.swing.JTextField txtPib;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        txtAdresa.setText("");
        txtPib.setText("");
        txtBrojTelefona.setText("");
        txtEmailKlijenta.setText("");
        txtNazivKlijenta.setText("");
        
        txtAdresa.setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        txtPib.setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        txtBrojTelefona.setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        txtEmailKlijenta.setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        txtNazivKlijenta.setBorder(BorderFactory.createLineBorder(Color.black,1,true));
        
        txtPib.setEditable(true);
        
        btnIzmeni.setEnabled(false);
        btnObrisi.setEnabled(false);
        btnSacuvaj.setEnabled(true);
    }

    private void pretrazi() {
        String pretraga = txtPretraga.getText();
        Klijent klijent = new Klijent();
        klijent.setNazivKlijenta(pretraga);
        
        ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.PRETRAZI_KLIJENTA, klijent);
        List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
        
        ModelTabeleKlijenti mt = (ModelTabeleKlijenti) tblKlijenti.getModel();
        mt.setListaKlijenata(lista);
    }

    private void srediFormuZaIzmenu(Klijent odabraniKlijent) {
        txtAdresa.setText(odabraniKlijent.getAdresa());
        txtPib.setText(odabraniKlijent.getPib()+"");
        txtBrojTelefona.setText(odabraniKlijent.getBrojTelefona());
        txtEmailKlijenta.setText(odabraniKlijent.getEmailKlijenta());
        txtNazivKlijenta.setText(odabraniKlijent.getNazivKlijenta());
        
        txtPib.setEditable(false);
        
        btnIzmeni.setEnabled(true);
        btnObrisi.setEnabled(true);
        btnSacuvaj.setEnabled(false);
    }
}
