/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.narudzbenice;

import domen.Klijent;
import domen.Narudzbenica;
import domen.OpstiDomenskiObjekat;
import domen.StavkaNarudzbenice;
import domen.Zaposleni;
import forme.glavna.GlavnaForma;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import konstante.Konstante;
import kontroler.Kontroler;
import modelitabele.ModelTabeleNarudzbenica;
import modelitabele.ModelTabeleStavki;
import transfer.ServerskiTransferObjekat;
import validation.FormValidator;

/**
 *
 * @author Miroslav
 */
public class RadSaNarudzbenicama extends javax.swing.JDialog {

    /**
     * Creates new form RadSaNarudzbenicama
     */
    public RadSaNarudzbenicama(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        UIManager.getLookAndFeelDefaults()
                .put("defaultFont", new Font("Arial", Font.BOLD, 18));
        initComponents();
        ucitajKlijente();
        ucitajZaposlene();
        ModelTabeleNarudzbenica mtn = new ModelTabeleNarudzbenica();
        tblNarudzbenice.setModel(mtn);
        ModelTabeleStavki mts = new ModelTabeleStavki();
        tabelaStavke.setModel(mts);
        txtUlogovaniNalog.setText(Kontroler.getInstance().getUlogovaniNalog().toString());
        srediFormu();
        pretrazi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNarudzbenice = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNarudzbenicaID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbKlijent = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbZaposleni = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUlogovaniNalog = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaStavke = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga po klijentu");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblNarudzbenice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNarudzbenice);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jLabel2.setText("Narudzbenica ID ");

        txtNarudzbenicaID.setEditable(false);

        jLabel3.setText("Datum");

        jLabel4.setText("Klijent");

        cmbKlijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Zaposleni");

        cmbZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Ukupno");

        txtUkupno.setEditable(false);

        jLabel7.setText("Ulogovani nalog");

        txtUlogovaniNalog.setEditable(false);

        tabelaStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaStavke);

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPretrazi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNarudzbenicaID)
                                            .addComponent(txtDatum)
                                            .addComponent(cmbKlijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtUkupno)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUlogovaniNalog))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnDodajStavku)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnObrisiStavku))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(jLabel2)
                    .addComponent(txtNarudzbenicaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtUlogovaniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodajStavku)
                            .addComponent(btnObrisiStavku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        DodajStavku ds = new DodajStavku((GlavnaForma) getParent(), true);
        ds.setForma(this);
        ds.pack();
        ds.setVisible(true);
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        obrisiStavku();
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        if (!FormValidator.getInstance().validateEmpty(txtDatum)) {
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        try {
            Date datum = sdf.parse(txtDatum.getText());
            ModelTabeleStavki mts = (ModelTabeleStavki) tabelaStavke.getModel();
            List<OpstiDomenskiObjekat> listaStavki = mts.getListaStavki();

            Zaposleni zap = (Zaposleni) cmbZaposleni.getSelectedItem();
            Klijent k = (Klijent) cmbKlijent.getSelectedItem();

            double ukupno = Double.parseDouble(txtUkupno.getText());

            Narudzbenica nar = new Narudzbenica(-1, datum, ukupno, k, zap, Kontroler.getInstance().getUlogovaniNalog(), listaStavki);

            ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.SACUVAJ_NARUDZBENICU, nar);

            JOptionPane.showMessageDialog(this, sto.getPoruka());

            if (sto.isUspesno()) {
                pretrazi();
                srediFormu();
            }

        } catch (ParseException ex) {
            Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        pretrazi();
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        int red = tblNarudzbenice.getSelectedRow();
        if (red != -1) {
            ModelTabeleNarudzbenica mtn = (ModelTabeleNarudzbenica) tblNarudzbenice.getModel();
            Narudzbenica nar = mtn.vratiNarudzbenicu(red);
            srediFormuZaIzmenu(nar);
        } else {
            System.out.println("Izaberi red");
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (!FormValidator.getInstance().validateEmpty(txtDatum)) {
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        try {
            Date datum = sdf.parse(txtDatum.getText());
            ModelTabeleStavki mts = (ModelTabeleStavki) tabelaStavke.getModel();
            List<OpstiDomenskiObjekat> listaStavki = mts.getListaStavki();

            Zaposleni zap = (Zaposleni) cmbZaposleni.getSelectedItem();
            Klijent k = (Klijent) cmbKlijent.getSelectedItem();

            double ukupno = Double.parseDouble(txtUkupno.getText());

            int narudzbenicaID = Integer.parseInt(txtNarudzbenicaID.getText());

            Narudzbenica nar = new Narudzbenica(narudzbenicaID, datum, ukupno, k, zap, Kontroler.getInstance().getUlogovaniNalog(), listaStavki);

            ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.IZMENI_NARUDZBENICU, nar);

            JOptionPane.showMessageDialog(this, sto.getPoruka());

            if (sto.isUspesno()) {
                pretrazi();
                srediFormu();
            }

        } catch (ParseException ex) {
            Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int narudzbenicaID = Integer.parseInt(txtNarudzbenicaID.getText());

        Narudzbenica nar = new Narudzbenica(narudzbenicaID, null, 0, null, null, Kontroler.getInstance().getUlogovaniNalog(), null);

        ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.OBRISI_NARUDZBENICU, nar);

        JOptionPane.showMessageDialog(this, sto.getPoruka());

        if (sto.isUspesno()) {
            pretrazi();
            srediFormu();
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadSaNarudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RadSaNarudzbenicama dialog = new RadSaNarudzbenicama(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKlijent;
    private javax.swing.JComboBox cmbZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaStavke;
    private javax.swing.JTable tblNarudzbenice;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtNarudzbenicaID;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtUkupno;
    private javax.swing.JTextField txtUlogovaniNalog;
    // End of variables declaration//GEN-END:variables

    private void ucitajKlijente() {
        Klijent klijent = new Klijent();
        klijent.setNazivKlijenta("");

        ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.PRETRAZI_KLIJENTA, klijent);

        List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
        cmbKlijent.removeAllItems();
        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            cmbKlijent.addItem(opstiDomenskiObjekat);
        }
    }

    private void ucitajZaposlene() {

        Zaposleni zap = new Zaposleni();

        ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.PRETRAGA_ZAPOSLENIH, zap);

        List<OpstiDomenskiObjekat> lista = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
        cmbZaposleni.removeAllItems();
        for (OpstiDomenskiObjekat opstiDomenskiObjekat : lista) {
            cmbZaposleni.addItem(opstiDomenskiObjekat);
        }
    }

    void dodajStavku(StavkaNarudzbenice stavka) {
        ModelTabeleStavki mts = (ModelTabeleStavki) tabelaStavke.getModel();
        mts.dodajStavku(stavka);
        popuniUkupno(mts.getListaStavki());
    }

    private void popuniUkupno(List<OpstiDomenskiObjekat> listaStavki) {
        double suma = 0.00;
        for (OpstiDomenskiObjekat opstiDomenskiObjekat : listaStavki) {
            StavkaNarudzbenice stavka = (StavkaNarudzbenice) opstiDomenskiObjekat;
            suma += stavka.getVrednost();
        }

        txtUkupno.setText(suma + "");
    }

    public void obrisiStavku() {

        int red = tabelaStavke.getSelectedRow();

        if (red != 1) {
            ModelTabeleStavki mts = (ModelTabeleStavki) tabelaStavke.getModel();
            mts.obrisiStavku(red);
            popuniUkupno(mts.getListaStavki());
        }
    }

    private void pretrazi() {
        String pretaga = txtPretraga.getText();
        Klijent k = new Klijent();
        k.setNazivKlijenta(pretaga);

        Narudzbenica nar = new Narudzbenica();
        nar.setKlijent(k);

        ServerskiTransferObjekat sto = Kontroler.getInstance().posaljiZahtevIPrimiOdgovor(Konstante.PRETRAGA_NARUDZBENICE, nar);

        List<OpstiDomenskiObjekat> listaNarudzbenica = (List<OpstiDomenskiObjekat>) sto.getOdgovor();
        ModelTabeleNarudzbenica mtn = (ModelTabeleNarudzbenica) tblNarudzbenice.getModel();
        mtn.setListaNarudzbenica(listaNarudzbenica);
    }

    public void srediFormu() {
        btnIzmeni.setEnabled(false);
        btnObrisi.setEnabled(false);
        btnSacuvaj.setEnabled(true);
    }

    private void srediFormuZaIzmenu(Narudzbenica nar) {
        txtDatum.setText(new SimpleDateFormat("dd.MM.yyyy").format(nar.getDatum()));
        cmbKlijent.setSelectedItem(nar.getKlijent());
        cmbZaposleni.setSelectedItem(nar.getZaposleni());
        txtUkupno.setText(nar.getUkupno() + "");
        txtNarudzbenicaID.setText(nar.getNarudzbenicaID() + "");

        ModelTabeleStavki mts = (ModelTabeleStavki) tabelaStavke.getModel();
        mts.setListaStavki(nar.getListaStavki());

        btnIzmeni.setEnabled(true);
        btnObrisi.setEnabled(true);
        btnSacuvaj.setEnabled(false);

    }
}
